language: generic 

#superuser do == Prozesse mit Rechten eines anderen Benutzers starten
sudo: required

services:
  - docker

  before_install:
    - docker build -t xnyze/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true xnyze/docker-react npm run test
